CREATE TABLE Unique_PlotPoints AS SELECT DISTINCT ICAO FROM PLANE_TRACKS;

ALTER TABLE Unique_PlotPoints ADD PRIMARY KEY (ICAO);

ALTER TABLE PLANE_TRACKS ADD FOREIGN KEY (ICAO) REFERENCES Unique_PlotPoints(ICAO);

CREATE SEQUENCE seq START WITH 1 INCREMENT BY 1;

commit;

CREATE TABLE PlotPoints AS SELECT seq.nextval, ICAO FROM Unique_PlotPoints;

ALTER TABLE PLOTPOINTS ADD CONSTRAINT airConstraint PRIMARY KEY (nextval);

ALTER TABLE PLANE_TRACKS ADD PKEY NUMBER;

DROP TABLE Unique_PlotPoints;

UPDATE PLANE_TRACKS
  SET PKEY = (select nextval from PLOTPOINTS where ICAO='300065')
  WHERE ICAO = '300065';

UPDATE PLANE_TRACKS
  SET PKEY = (select nextval from PLOTPOINTS where ICAO='6011')
  WHERE ICAO = '6011';
  
UPDATE PLANE_TRACKS
  SET PKEY = (select nextval from PLOTPOINTS where ICAO='300068')
  WHERE ICAO = '300068';
  
UPDATE PLANE_TRACKS
  SET PKEY = (select nextval from PLOTPOINTS where ICAO='3C5EE7')
  WHERE ICAO = '3C5EE7';
  
UPDATE PLANE_TRACKS
  SET PKEY = (select nextval from PLOTPOINTS where ICAO='40631A')
  WHERE ICAO = '40631A';

CREATE TABLE PLANETRACKS AS 
SELECT PKEY,ICAO,LATITUDE,LONGITUDE,IND,ALT,ALTT,ENGMOUNT,ENGTYPE,ENGINES,GALT,GND,ID,INHG,MIL,MLAT,POSTIME,SPD,SPDTYP,SPECIES,TT,TRAK,TRKH,VSI,VSIT,WTC
FROM PLANE_TRACKS;

ALTER TABLE PLANETRACKS
ADD CONSTRAINT SetForeignKey
   FOREIGN KEY (PKEY)
   REFERENCES PLOTPOINTS (nextval);
