CREATE TABLE PLANETRACKS AS 
SELECT PKEY,ICAO,LATITUDE,LONGITUDE,IND,ALT,ALTT,ENGMOUNT,ENGTYPE,ENGINES,GALT,GND,ID,INHG,MIL,MLAT,POSTIME,SPD,SPDTYP,SPECIES,TT,TRAK,TRKH,VSI,VSIT,WTC
FROM PLANE_TRACKS;
