CREATE TABLE Unique_PlotPoints AS SELECT DISTINCT ICAO FROM PLANE_TRACKS;

ALTER TABLE Unique_PlotPoints ADD PRIMARY KEY (ICAO);

ALTER TABLE PLANE_TRACKS ADD FOREIGN KEY (ICAO) REFERENCES Unique_PlotPoints(ICAO);
