#!/bin/bash

su cloudera <<!
cloudera

javac -cp /usr/lib/hadoop/*:/usr/lib/hadoop/client-0.20/* -d /home/cloudera/MSTIFF_Code /home/cloudera/MSTIFF_Code/GET_MST_mod.java
jar -cvf GET_MST_mod.jar -C /home/cloudera/MSTIFF_Code/ .

# move JAR File to specified directory on the vm
mv GET_MST_mod.jar /home/cloudera/MSTIFF_Code

#su cloudera <<!
#cloudera

#chown cloudera:cloudera /home/cloudera/MSTIFF_Code/GET_MST_MOD.jar
#echo $?
#chmod ug+rw /home/cloudera/MSTIFF_Code/GET_MST_MOD.jar
#echo $?
#!

hadoop jar /home/cloudera/MSTIFF_Code/GET_MST_mod.jar GET_MST_mod /user/cloudera/MSTIFF_Code /user/cloudera/successfulOutput1
echo $?
#!
